name: road_ize
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.10.1
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.13
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.0-dev.2
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.14.4
  flutter_login: ^1.0.14
  image_picker: ^0.6.7+17
  firebase_storage: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

